# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('internal_name', models.CharField(max_length=255, verbose_name='Internal name')),
                ('enabled', models.BooleanField(default=False, verbose_name='Is widget enabled')),
            ],
        ),
    ]
