# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('box_office_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Box office price')),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Ticket', verbose_name='Tickets'),
        ),
    ]
