# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160825_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='internal_name',
            field=models.TextField(verbose_name='Internal name'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
