# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 10:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20160826_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 26, 10, 24, 23, 261047, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 26, 10, 24, 25, 846259, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
