# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160826_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='tickets',
        ),
    ]
