# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_barcodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeimage',
            name='format',
            field=models.CharField(choices=[('ean13', 'EAN-8'), ('ean8', 'EAN-13'), ('code128', 'Code-128'), ('Starndard39', 'Starndard-39')], default='ean13', max_length=21, verbose_name='Barcode format'),
        ),
    ]
