# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20160907_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
