# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('home', '0012_auto_20160907_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fails_count', models.IntegerField(blank=True, null=True, verbose_name='Failed bids count')),
                ('last_fail', models.DateTimeField(auto_now=True, null=True, verbose_name='Last failed bid date')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
    ]
