# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160901_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Planned', 'Planned'), ('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Draft', max_length=11, verbose_name='Widget status'),
        ),
    ]
