# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_widget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Dynamic', 'Dynamic')], default='Dynamic', max_length=7, verbose_name='Widget type'),
        ),
    ]
