# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0011_auto_20160830_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='Session key')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bid price')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket', verbose_name='Ticket')),
            ],
        ),
    ]
