# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 31, 7, 17, 33, 512849, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
