# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('PAID', 'paid'), ('REJECTED', 'rejected')], default='ACCEPTED', max_length=8, verbose_name='Status'),
        ),
    ]
