# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('number_of_tickets', models.SmallIntegerField(verbose_name='Number of tickets')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('article_title', models.TextField(blank=True, null=True, verbose_name='Article title')),
                ('first_name', models.TextField(blank=True, null=True, verbose_name='First name')),
                ('last_name', models.TextField(blank=True, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='ACCEPTED', max_length=8, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid', verbose_name='Bid'),
        ),
    ]
