# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20160905_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='number_of_tickets',
            field=models.SmallIntegerField(default=10, verbose_name='Number of tickets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('PAID', 'paid')], default='ACCEPTED', max_length=8, verbose_name='Status'),
        ),
    ]
