# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20160905_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[(0, 'accepted'), (1, 'rejected'), (2, 'paid')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
