# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_auto_20160906_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('PAID', 'paid')], default='REJECTED', max_length=8, verbose_name='Status'),
        ),
    ]
