# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_buyer'),
        ('tickets', '0013_auto_20160912_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='session_key',
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Buyer', verbose_name='Buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Article', verbose_name='Article'),
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='ticket',
            new_name='article',
        ),
    ]
