# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0010_auto_20160913_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='article_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
