# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0011_auto_20160913_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_of_tickets',
        ),
    ]
