# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('box_office_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Box office price')),
            ],
        ),
    ]
