# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
