# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 09:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20160829_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='template',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
