# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 12:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20160829_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(null=True, upload_to='/media/', verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='template',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Template'),
        ),
    ]
