# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20160829_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='/media/', verbose_name='PDF file'),
        ),
    ]
