# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20160829_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='max_bid_attempts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Amount of times user can bid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='min_accepted_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Box office price'),
        ),
    ]
