# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_widget_tickets'),
        ('tickets', '0009_auto_20160830_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Widget', verbose_name='Widget'),
        ),
    ]
