# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='internal_name',
            field=models.TextField(default='Internal name', verbose_name='Internal name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='min_accepted_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Min accepted bid'),
        ),
    ]
