# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20160830_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='/app/media', verbose_name='PDF file'),
        ),
    ]
