# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_barcode_created_by'),
        ('tickets', '0012_auto_20160830_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='barcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Barcode'),
            preserve_default=False,
        ),
    ]
