# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20160830_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Article',
        ),
    ]
