# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weekday_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20160912_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Valid to')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', weekday_field.fields.WeekdayField(blank=True, max_length=14, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Price in EUR')),
                ('min_tickets', models.IntegerField(blank=True, null=True, verbose_name='Minimum tickets per customer')),
                ('max_tickets', models.IntegerField(blank=True, null=True, verbose_name='Maximum tickets per customer')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Displayed discount in %')),
                ('min_accepted_bid', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Min accepted bid')),
                ('related_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Discount')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='box_office_price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='min_accepted_bid',
        ),
        migrations.AddField(
            model_name='article',
            name='countdown_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Countdown time (in seconds)'),
        ),
        migrations.AddField(
            model_name='article',
            name='unblock_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unblock time (in minutes)'),
        ),
        migrations.AddField(
            model_name='discount',
            name='related_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Article'),
        ),
    ]
